.\" -*- nroff -*-
.TH NOIP2 8 "October 2007"
.SH NAME
noip2 - No-IP.com Dynamic DNS Update Client (DUC)
.SH SYNOPSIS
.BI "noip2 " "[ -C [ -F][ -Y][ -L hosts_groups][ -U #min][ -u username][ -p password][ -x progname]][ -c file][ -d][ -D pid][ -i addr][ -S][ -M][ -h]"
.SH DESCRIPTION
.PP
The No-IP.com Dynamic DNS Update Client (DUC) periodically checks the
local IP address to see if it has changed. If the IP address has
changed, the client notifies the No-IP.com DNS servers and updates the
IP address corresponding to the user's No-IP/No-IP+ configured
hostname(s).
.PP
A valid No-IP.com account is required.
.PP
The client communicates with the No-IP.com server over TCP on port
8245 (outgoing). 
.SH OPTIONS
.TP
.B -C
create configuration data file
.TP
.B -F
force NAT off
.TP
.B -Y
select all hosts/groups
.TP
.B -L hosts_groups
select supplied hosts/groups (Example:
.I -L some_domain.no-ip.com,Group1,Group2,another_domain.no-ip.biz\f[R])
.TP
.B -U minutes
set update interval in minutes (Example: Set
.I -U 30
for
.I 30
minutes)
.TP
.B -u username
use supplied username
.TP
.B -p password
use supplied password
.TP
.B -x executable
use supplied executable
.TP
.B -c config_file
use alternate path to store configuration data file (Example:
.I -c /path/to/noip2.conf_file\f[R])
.TP
.B -d
increase debug verbosity
.TP
.B -D processID
toggle debug flag for PID
.TP
.B -i IPaddress
use supplied address. This option is also useful to run the client once and exit.
.TP
.B -I interface
use supplied interface
.TP
.B -S
show configuration data
.TP
.B -M
permit multiple instances
.TP
.B -K processID
terminate instance PID
.TP
.B -z
activate shm dump code
.TP
.B -h
Display usage information
.SH FILES
.TP
.I /var/lib/noip2/noip2.conf
Configuration data file, generated by running
.B
noip2 \-C
(binary file).
.SH LICENSE
.B noip2
can be distributed under the terms of the GPLv2 license. A copy of the
license can be found under /usr/share/common\-licenses/GPL\-2
.SH "SEE ALSO"
.BR /usr/share/doc/noip2
