#!/bin/sh -e

case "$1" in
	remove|purge|deconfigure)
		rm -f /var/lib/noip2/noip2.conf
		;;
	upgrade)
	        ;;
	abort-remove|abort-deconfigure)
		;;
	*)
		echo "postrm called with unknown argument \'$1'" >&2
		exit 0
		;;
esac

#DEBHELPER#
